### ISSUE TITLE
resource-server sample stops working if 4.7 framework is used

### ISSUE THREAD

**Issue by amikulich** [okta/samples-aspnet#17] opened 2019-02-27 07:58 UTC
I downloaded your repository with samples and was able to setup resource-server sample with my okta organization settings. The sample application targets 4.6.1 .Net framework, but when I tried to upgrade to 4.7 authentication stopped working. Worth mentioning that there is no exception thrown but even when you pass correct access_token within the request Claims are not parsed and user is not authenticated

Steps to reproduce:
1) Download and open resource-server solution (okta-aspnet-webapi-example.sln)
2) Target okta-aspnet-webapi-example.csproj project to .Net 4.7
3) Rebuild project
4) Make sure .Net 4.7 is targeted in web.config <system.web> section like this:  
`<compilation debug="true" targetFramework="4.7"/>`
`<httpRuntime targetFramework="4.7"/>`

5) Put your okta:OktaDomain in web.config
6) Run application and try to call messages api with valid access_token
Expected result: RequestContext.Principal.Identity as ClaimsIdentity returns authenticated identity with claims
Actual: user is not authenticated

**Comment by laura-rodriguez** [comment] 2019-02-27 19:28
Hi @amikulich,
Are you using any of our front-end samples to call the messages API?

**Comment by laura-rodriguez** [comment] 2019-02-27 19:31
I forgot to mention that the `Authorize` attribute is missing the `MessageController`, so it shouldn't ask for authentication at all. We've already submitted a PR to fix it: https://github.com/okta/samples-aspnet/pull/18.

**Comment by colinmcorcoran** [comment] 2019-04-01 19:21
I too am seeing this behavior on 4.7
I've dug in a bit and am seeing that it looks like the ValidateSignature call here is failing: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L866

**Comment by nbarbettini** [comment] 2019-04-16 14:51
@colinmcorcoran Thanks for digging that up. What does your configuration look like? 

@amikulich I'm wondering if there is a configuration error here that's getting swallowed for some reason. Signature validation shouldn't fail for a valid token, but it must be a token issued by a Custom Authorization Server and the `issuer` URI must be correct.

**Comment by laura-rodriguez** [comment] 2019-05-21 15:20
@colinmcorcoran @amikulich are you still having issues with 4.7? I wasn't able to reproduce this issue.

**Comment by laura-rodriguez** [comment] 2020-08-04 14:08
Closing this now. Feel free to reopen if this is still an issue.

**Closed by laura-rodriguez** 2020-08-04 14:08 UTC
Labels: cannot-reproduce, question
